config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:create, :index, :new, :show] do
    resources :reviews, only: [:new, :create]
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, :address, :category, presence: true
    validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
        message: "%{value} is not a category" }      
    has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
    validates :content, :rating, presence: true
    belongs_to :restaurant
    validates :rating, numericality: { only_integer: true}
    # A review’s rating must be a number between 0 and 5.
    validates :rating, inclusion: 0..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_area :phone_number, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_area :category, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
<div class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">
      <small>
        <% count = 0 %>
        <% 5.times do %>
          <% if review.rating > count %>
            <i class="fas fa-star"></i>
          <% else %>
            <i class="far fa-star"></i>
          <% end %>
          <% count += 1 %>
        <% end %>
      </small>
      <p><%= review.content %></p>
    </li>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h1>My restaurants</h1>

<ul id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <li> <%= restaurant.name restaurant.address restaurant.phone_number restaurant.category %>  </li>
  <% end %>
</ul>

<%= link_to new_restaurant_path do %>
  <i class="fa fa-plus"></i> Add a new restaurant
<% end %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p class="well"><%= @restaurant.address %></p>
<p class="well"><%= @restaurant.phone_number %></p>
<p class="well"><%= @restaurant.category %></p>

<hr>
<%= link_to restaurants_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>